[pytest]
testpaths = tests
addopts = -v --alluredir=../reports/ui/allure-results --html=../reports/ui/report.html --self-contained-html
markers =
    smoke: scénarios critiques
    popup: alertes et modales
    frames: frames / iframes
